# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataPath: '/mnt/input/home/data'
modelPath: '/mnt/input/home/models'
modelName: 'mnist'
outputPath: '/mnt/output/experiment'
inputFormat: 'pb'

containerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

workersCount: 1

resources:
  requests:
    cpu: 38
    memory: 120Gi
  limits:
    cpu: 38
    memory: 120Gi

cpu: null
memory: null

batch_wrapper_resources:
  requests:
    cpu: 2
    memory: 1Gi

wrapper_cpu: null
wrapper_memory: null

experimentName: {{ NAUTA.ExperimentName }} 
podCount: 2
registryPort: {{ NAUTA.RegistryPort }}

logLevel: 'INFO'

cpu_fraction: 0.5
memory_fraction: 0.5
