# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataPath: '/mnt/input/home/data'
modelPath: '/mnt/input/home/models'
modelName: 'mnist'
outputPath: '/mnt/output/experiment'
inputFormat: 'pb'

containerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ DLS4e.ExperimentImage }}

workersCount: 1

resources:
  requests:
    cpu: 38
    memory: 120Gi
  limits:
    cpu: 38
    memory: 120Gi

batch_wrapper_resources:
  requests:
    cpu: 2
    memory: 1Gi

experimentName: {{ DLS4e.ExperimentName }} 
podCount: 2
registryPort: {{ DLS4e.RegistryPort }}

logLevel: 'INFO'
