apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    draft: {{ .Values.draft }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ template "name" . }}
    draft: {{ .Values.draft }}
    release: {{ .Release.Name }}
    runName: {{ .Release.Name }}
  type: ClusterIP