apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-etcd-gc
  labels:
    app: {{ .Chart.Name }}-etcd-gc
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}-etcd-gc
            release: {{ .Release.Name }}
            chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
            heritage: {{ .Release.Service }}
            nauta_app_name: etcd-gc
        spec:
          serviceAccount: {{ .Release.Name }}-{{ .Chart.Name }}
          containers:
          - name: {{ .Chart.Name }}
            image: {{ required "NAUTA Registry is required" .Values.global.nauta_registry }}/{{ required "NAUTA etcd_gc image is required" .Values.etcd_gc_image }}
            imagePullPolicy: "IfNotPresent"
            command:
            - sh
            - -c
            - kubectl exec -i $(kubectl get --no-headers=true pods -l app=experiment-service-etcd -n nauta -o custom-columns=:metadata.name) -n nauta -- sh -c 'if [ "$(ETCDCTL_API=3 etcdctl alarm list | grep -c '\''alarm:NOSPACE'\'')" -ne 0 ]; then echo "Alarm NOSPACE, compacting"; rev=$(ETCDCTL_API=3 etcdctl --endpoints=:2379 endpoint status --write-out="json" | egrep -o '\''"revision":[0-9]*'\'' | egrep -o '\''[0-9].*'\''); ETCDCTL_API=3 etcdctl compact $rev; ETCDCTL_API=3 etcdctl defrag; ETCDCTL_API=3 etcdctl alarm disarm; else echo "No alarms found. OK"; fi'
          restartPolicy: OnFailure
          tolerations:
          - key: "master"
            operator: "Exists"
            effect: "NoSchedule"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: master
                    operator: In
                    values:
                    - "True"
