apiVersion: v1
appVersion: 0.12.1
description: A Helm chart for deploying Horovod
home: https://eng.uber.com/horovod/
maintainers:
- email: cheyang@163.com
  name: cheyang
name: multinode-tf-training-horovod
sources:
- https://github.com/uber/horovod
- https://github.com/uber/horovod/blob/master/docs/docker.md
version: 0.2.1