---

- name: Find base image in repo
  environment: "{{ proxy }}"
  uri:
    url: "{{ docker_repository_url }}/v2/{{ docker_version_prefix }}/{{ name }}/manifests/{{ docker_images_remote_tags[name] }}"
    status_code: 200,404
    validate_certs: False
  register: image_present
  when: not docker_defined_images[name]

- name: Add image definition
  set_fact:
    docker_images_remote_exists: "{{ docker_images_remote_exists | combine({ name: image_present.status == 200 }) }}"
  when: not docker_defined_images[name]

- name: Add image definition
  set_fact:
    docker_images_remote_exists: "{{ docker_images_remote_exists | combine({ name: True }) }}"
  when: docker_defined_images[name]
