---

- name: Set async task
  set_fact:
    docker_async_tasks: {}

- name: Load all images
  vars:
    name: "{{ item.key }}"
    image: "{{ item.value }}"
  include_tasks: "load_image.yml"
  with_dict: "{{ images }}"
  when:
    - docker_repository_cache.enabled
    - docker_images_remote_exists[name]
    - not docker_defined_images[name]

- name: Wait for tasks
  vars:
    name: "{{ item.key }}"
    task_id: "{{ item.value }}"
  include_tasks: wait.yml
  with_dict: "{{ docker_async_tasks }}"
  when: docker_repository_cache.enabled
