---

- name: Push image {{ name }} as 127.0.0.1:{{ registry_port }}/{{ name }}:{{ image.version }}
  docker_image:
    name: "{{ docker_repository_registry }}/{{ docker_version_prefix }}/{{ name }}:{{ docker_images_remote_tags[name] }}"
    repository: "127.0.0.1:{{ registry_port }}/{{ name }}:{{ image.version }}"
    pull: False
    push: "{{ image.push | default(True) }}"
    timeout: "{{ docker_timeout }}"
    force: True
  register: push_async
  failed_when: "'ansible_job_id' not in push_async"
  async: 1800
  poll: 0

- set_fact:
    docker_async_tasks: "{{ docker_async_tasks | combine({name: push_async.ansible_job_id}) }}"
