---

- name: Set async task
  set_fact:
    docker_async_tasks: {}

- name: Save all images
  vars:
    name: "{{ item.key }}"
    image: "{{ item.value }}"
  include_tasks: "save_image.yml"
  with_dict: "{{ images }}"
  when: not docker_images_remote_exists[name]

- name: Wait for tasks
  vars:
    name: "{{ item.key }}"
    task_id: "{{ item.value }}"
  include_tasks: wait.yml
  with_dict: "{{ docker_async_tasks }}"

- name: Save image to a file {{ build_logs }}/container_images.txt for IP Plan report generator
  lineinfile:
    dest: '{{ build_logs }}/container_images.txt'
    line: '{{ docker_repository_registry }}/{{ docker_version_prefix }}/{{ item.key }}:{{ docker_images_remote_tags[item.key] }}'
    state: present
    create: true
  with_dict: "{{ images }}"
  when: build_logs | default(False)

