apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-model-server
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    runName: {{ .Release.Name }}
    batchType: server
spec:
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
        scheduling.k8s.io/group-name: {{ .Release.Name }}-podgroup
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "chart_version" . }}
        heritage: {{ .Release.Service }}
        runName: {{ .Release.Name }}
        batchType: server
    spec:
      schedulerName: kube-batch
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.clusterRepository }}"
          env:
            - name: MODEL_NAME
              value: "{{ .Values.modelName }}"
            - name: MODEL_BASE_PATH
              value: "/models"
            - name: MODEL_PATH
              value: "{{ .Values.modelPath }}"
          command: ["tf_serving_nauta"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: input-home
              mountPath: /mnt/input/home
              readOnly: True
            - name: input-public
              mountPath: /mnt/input/root
              readOnly: True
            - name: output-home
              mountPath: /mnt/output/home
            - name: output-public
              mountPath: /mnt/output/root
              readOnly: True
            - name: output-public
              mountPath: /mnt/output/root/public
              subPath: public
            - name: input-public
              mountPath: /mnt/input/root/public
              subPath: public
            - name: output-home
              mountPath: /mnt/output/experiment
              subPath: {{ .Values.experimentName }}
            - name: shared-data
              mountPath: /pod-data
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: {{ default .Values.resources.requests.cpu .Values.cpu}}
              memory: {{ default .Values.resources.requests.memory .Values.memory }}
            limits:
              cpu: {{ default .Values.resources.limits.cpu .Values.cpu }}
              memory: {{ default .Values.resources.limits.memory .Values.memory }}
        - name: sidecar
          image: "127.0.0.1:{{ .Values.registryPort }}/nauta/tf-serving-sidecar:v1.0.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BATCH_WRAPPER_JOB_NAME
            value: {{ .Release.Name }}-batch-wrapper
          command: ["/bin/bash", "-c", "python3.6 main.py && exit"]
          volumeMounts:
          - name: shared-data
            mountPath: /pod-data
      restartPolicy: Never
      volumes:
        - name: input-home
          persistentVolumeClaim:
            claimName: input-home
        - name: input-public
          persistentVolumeClaim:
            claimName: input-public
        - name: output-home
          persistentVolumeClaim:
            claimName: output-home
        - name: output-public
          persistentVolumeClaim:
            claimName: output-public
        - name: shared-data
          emptyDir: {}
  backoffLimit: 0
