---

kubernetes_default_admission_control:
  - NamespaceLifecycle
  - NamespaceExists
  - ServiceAccount
  - LimitRanger
  - ResourceQuota
  - DefaultStorageClass
  - Priority
  - PodNodeSelector
  - PodPreset

kubernetes_default_feature_gates:
  PodPriority: false # enable POD prioritizing
  TaintBasedEvictions: true # secured schedule
  TaintNodesByCondition: true
  VolumeScheduling: true

kubernetes_default_runtime_config:
  scheduling.k8s.io/v1alpha1: true
  settings.k8s.io/v1alpha1: true

kubernetes_calculated_admission_control: "{{ (kubernetes_default_admission_control + kubernetes_admission_control | default([])) | unique }}"
kubernetes_calculated_feature_gates: "{{ (kubernetes_default_feature_gates | combine(kubernetes_feature_gates | default({}))) }}"
kubernetes_calculated_runtime_config: "{{ (kubernetes_default_runtime_config | combine(kubernetes_runtime_config | default({}))) }}"

kubernetes_anonymous_access: True

cpu_manager_policy: static
system_reserved: "cpu=500m"
kube_reserved: "cpu=500m"
cgroups_per_qos: true
