---

- name: "{{ message_label }} Install package"
  include_tasks: yum_nauta_install.yml
  vars:
    packages:
      - nauta-kubernetes-server-1.10.11
      - nauta-kubernetes-client-1.10.11
      - nauta-helm-2.9.1
    handlers:
      - Reload Systemd
      - Restart Kubernetes Apiserver
      - Restart Kubernetes Scheduler
      - Restart Kubernetes Controller
