apiVersion: batch/v1
kind: Job

metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    draft: {{ .Values.draft }}
    runName: {{ .Release.Name }}
spec:
  replicas: {{ .Values.workersCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "chart_version" . }}
        draft: {{ .Values.draft }}
        heritage: {{ .Release.Service }}
        runName: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.clusterRepository }}:{{ .Values.image.tag }}"
          env:
            - name: MODEL_NAME
              value: "{{ .Values.modelName }}"
            - name: MODEL_BASE_PATH
              value: "/models"
            - name: MODEL_PATH
              value: "{{ .Values.modelPath }}"
          command: ["tf_serving_dls4e"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.grpcContainerPort }}
              name: grpc-port
            - containerPort: {{ .Values.restContainerPort }}
              name: rest-port
          volumeMounts:
            - name: input-home
              mountPath: /mnt/input/home
              readOnly: True
            - name: input-public
              mountPath: /mnt/input/root
              readOnly: True
            - name: output-home
              mountPath: /mnt/output/home
            - name: output-public
              mountPath: /mnt/output/root
            - name: output-home
              mountPath: /mnt/output/experiment
              subPath: {{ .Values.experimentName }}
          securityContext:
            privileged: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: OnFailure
      priorityClassName: low-priority
      volumes:
        - name: input-home
          persistentVolumeClaim:
            claimName: input-home
        - name: input-public
          persistentVolumeClaim:
            claimName: input-public
        - name: output-home
          persistentVolumeClaim:
            claimName: output-home
        - name: output-public
          persistentVolumeClaim:
            claimName: output-public
  backoffLimit: 5
