# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

modelPath: ''
modelName: ''

restContainerPort: 8501
grpcContainerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

workersCount: 1

resources:
  requests:
    cpu: 7
    memory: 20Gi
  limits:
    cpu: 7
    memory: 20Gi

cpu: null
memory: null

experimentName: {{ NAUTA.ExperimentName }} 
podCount: 1
