---

- name: Generate root for certs
  include_tasks: kind.yml
  with_items:
    - kubernetes
    - api-proxy
    - consul
    - etcd
  loop_control:
    loop_var: kind

- name: Generate certs for apiservice
  include_tasks: cert.yml
  vars:
    name: "apiservice"
    common_name: "{{ kubernetes_network.svc_list.apiservice.consul_name }}"
    subject_alt_name:
      DNS.1: "{{ kubernetes_network.svc_list.apiservice.consul_name }}"
      DNS.2: "kubernetes"
      DNS.3: "kubernetes.default"
      DNS.4: "kubernetes.default.svc"
      DNS.5: "kubernetes.default.svc.{{ k8s_domain }}.{{ domain }}"
      IP.1: "{{ kubernetes_network.svc_list.apiservice.ip }}"
      IP.2: "{{ dls_configuration.external_interface.ipv4_address }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
      - nonRepudiation
    extended_key_usage:
      - clientAuth
      - serverAuth
  with_items:
    - kubernetes
    - api-proxy
  loop_control:
    loop_var: kind

- name: Generate certs for service
  include_tasks: cert.yml
  vars:
    name: "service"
    common_name: "service"
    subject_alt_name:
      DNS.1: "service"
    key_usage:
      - digitalSignature
      - keyEncipherment
      - nonRepudiation
    extended_key_usage:
      - clientAuth
  with_items:
    - kubernetes
  loop_control:
    loop_var: kind

- name: Generate certs for registry
  include_tasks: cert.yml
  vars:
    name: "registry"
    common_name: "registry"
    subject_alt_name:
      DNS.1: "registry.service.{{ nodes_domain }}.{{ domain }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
      - nonRepudiation
    extended_key_usage:
      - clientAuth
  with_items:
    - consul
  loop_control:
    loop_var: kind

- include_tasks: synchronize-ca.yml
  with_items:
    - kubernetes
    - api-proxy
    - consul
    - etcd
  loop_control:
    loop_var: kind
