---

helm_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz
helm_sha: 02a4751586d6a80f6848b58e7f6bd6c973ffffadc52b4c06652db7def02773a1
helm_local: "{{ build_dir }}/helm"
