---

gcp:
  region: "europe-west1"
  zone: "europe-west1-b"

  external_username: "nauta"

  gateway_type: "n1-highmem-4"
  testnode_type: "n1-standard-2"
  nfs_type: "n1-standard-2"
  nfs_disk_size: "400"

  internal_username: "nauta"

  pool_type: "n1-standard-16"
  pool_size: "1"
  pool_min_cpu_platform: "Intel Skylake"

  generate_test_node: False
  testnode_image: ""
