---

push_local: False
tag_local: True
create_package: False

images:
  compiler/centos7:
    version: "7.4.1708"
    image: "centos:7.4.1708"
    method: "pull"
  compiler/centos7-ready:
    version: "7.4.1708"
    required:
      BASE_IMAGE: "compiler/centos7"
    directory: "{{ playbook_dir }}/../../compile-containers/centos7"
    method: build
  compiler/ubuntu16:
    version: "16.04"
    image: "ubuntu:16.04"
    method: "pull"
  compiler/ubuntu16-ready:
    version: "16.04"
    required:
      BASE_IMAGE: "compiler/ubuntu16"
    directory: "{{ playbook_dir }}/../../compile-containers/ubuntu16"
    method: build
