---

local_images:
  core/flannel:
    version: "v0.9.1"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/flannel"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/flannel"
  core/kube-proxy:
    version: "v1.10.6"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/kube-proxy"
  core/pause:
    version: "3.1"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-addons"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/pause"
  core/addon-resizer:
    version: "1.7"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-addons"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/addon-resizer"
  core/tiller:
    version: "v2.9.1"
    required:
      BASE_IMAGE: "shared/build/tiller"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/tiller"
  core/heapster:
    version: "v1.4.3"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/heapster"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/heapster"
  core/defaultbackend:
    version: "1.4"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/defaultbackend"
  core/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos"
      INGRESS_DATA_IMAGE: "shared/build/ingress"
      NGINX_DATA_IMAGE: "shared/build/nginx"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/ingress-nginx"
  core/kube-dns:
    version: "1.14.8"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-addons"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/kube-dns"
  core/dnsmasq-nanny:
    version: "1.14.8"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-addons"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/dnsmasq-nanny"
  core/dns-sidecar:
    version: "1.14.8"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-addons"
    directory: "{{ playbook_dir }}/../../platform-containers/dns-sidecar"
    method: build
  core/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/etcd"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/etcd"
  core/dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/kubernetes-dashboard"
    directory: "{{ playbook_dir }}/../../platform-containers/kubernetes-dashboard"
    method: build
  core/registry:
    version: "v2"
    #image: "registry:2"
    required:
      BUILD_IMAGE: "shared/centos/build-go"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/registry"

chart_values:
  features: {}

subcharts:
  dls4e-platform:
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/dashboard"
      chart_values:
        image: "{{ image_local_url['core/dashboard'] }}"
    flannel:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/flannel"
      chart_values:
        image: "{{ image_local_url['core/flannel'] }}"
    heapster:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/heapster"
      chart_values:
        image: "{{ image_local_url['core/heapster'] }}"
        nanny_image: "{{ image_local_url['core/addon-resizer'] }}"
    samba-forward:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../platform-charts/samba-forward"
    admin:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../platform-charts/admin"
    nfs:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/nfs"
    skydns:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/skydns"
      chart_values:
        kubedns_image: "{{ image_local_url['core/kube-dns'] }}"
        nanny_image: "{{ image_local_url['core/dnsmasq-nanny'] }}"
        sidecar_image: "{{ image_local_url['core/dns-sidecar'] }}"
    ingress:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/ingress"
      chart_values:
        ingress_image: "{{ image_local_url['core/ingress'] }}"
        defaultbackend_image: "{{ image_local_url['core/defaultbackend'] }}"
