# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TensorBoardPort: 8888
TensorIPythonPort: 6006

commandline:
  args:
    {% for arg in NAUTA.CommandLine %}
    - {{ arg }}
    {% endfor %}

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

service:
  type: ClusterIP

worker_resources:
  requests:
    cpu: 38
    memory: 187208842179
  limits:
    cpu: 38
    memory: 187208842179

worker_cpu: null
worker_memory: null

ps_resources:
  requests:
    cpu: 38
    memory: 187208842179
  limits:
    cpu: 38
    memory: 187208842179

ps_cpu: null
ps_memory: null

sidecar_resources:
  requests:
    cpu: 0.01
    memory: 100Mi
  limits:
    cpu: 0.01
    memory: 100Mi

sidecar_cpu: null
sidecar_memory: null


experimentName: {{ NAUTA.ExperimentName }} 
registryPort: {{ NAUTA.RegistryPort }}

workersCount: 3
sidecarLoggingLevel: "WARNING"
pServersCount: 1

cpu_fraction: 1
memory_fraction: 1
