# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

modelPath: ''
modelName: ''

restContainerPort: 8501
grpcContainerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

workersCount: 1

resources:
  requests:
    cpu: 19
    memory: 94.7Gi
  limits:
    cpu: 19
    memory: 94.7Gi

cpu: null
memory: null

experimentName: {{ NAUTA.ExperimentName }} 
podCount: 1

cpu_fraction: 0.5
memory_fraction: 0.5
